#!/usr/bin/python
#
# Call the command line interface for Epydoc.
#

# Make sure that we don't get confused between an epydoc.py script and
# the real epydoc package.
import sys, os.path

from docutils.nodes import NodeVisitor

NodeVisitor.optional = ('note')

if os.path.exists(os.path.join(sys.path[0], 'epydoc.py')):
    del sys.path[0]

from epydoc.cli import cli
cli()

